// Model-free checks of the Parler delay-pattern module against fixtures
// generated by scripts/dump-parler-reference.py from the REAL HF classes.

#include "parler_delay.h"
#include "npy.h"
#include "json.hpp"

#include <cmath>
#include <cstdio>
#include <fstream>
#include <string>
#include <vector>

using namespace tts_cpp::parler::detail;
using json = nlohmann::json;

static int fail(const char * msg) {
    fprintf(stderr, "test_parler_delay: FAIL: %s\n", msg);
    return 1;
}

int main(int argc, char ** argv) {
    if (argc < 2) {
        fprintf(stderr, "usage: %s REF_DIR\n", argv[0]);
        return 2;
    }
    const std::string ref_dir = argv[1];

    delay_config cfg;
    cfg.n_codebooks = 9;
    cfg.bos_id = 1025;
    cfg.eos_id = 1024;
    cfg.pad_id = 1024;

    // ---- delay mask vs HF build_delay_pattern_mask (max_length 24) ----
    {
        delay_config c = cfg;
        c.max_length = 24;
        std::vector<int32_t> mask = build_delay_mask(c);
        npy_array ref = npy_load(ref_dir + "/delay_mask_len24.npy");
        if (ref.shape.size() != 2 || ref.shape[0] != 9 || ref.shape[1] != 24) {
            return fail("delay_mask_len24 fixture shape");
        }
        const int64_t * r = reinterpret_cast<const int64_t *>(ref.data.data());
        for (size_t i = 0; i < mask.size(); ++i) {
            if ((int64_t) mask[i] != r[i]) {
                fprintf(stderr, "mask mismatch at %zu: got %d ref %lld\n",
                        i, mask[i], (long long) r[i]);
                return fail("delay mask");
            }
        }
        npy_array st = npy_load(ref_dir + "/delay_start_ids.npy");
        const int64_t * s = reinterpret_cast<const int64_t *>(st.data.data());
        for (int k = 0; k < 9; ++k) {
            if (s[k] != cfg.bos_id) return fail("start ids");
        }
    }

    // ---- logits processor trace vs the real ParlerTTSLogitsProcessor ----
    {
        std::ifstream f(ref_dir + "/logits_proc_trace.json");
        if (!f) return fail("missing logits_proc_trace.json");
        json j = json::parse(f);
        const int vocab = 1088;
        delay_config c = cfg;
        c.max_length = 64;
        c.min_new_tokens = 0; // trace was produced without the min-new-tokens warper
        delay_state st(c);
        int step_idx = 0;
        for (const auto & step : j["trace"]) {
            // replay the recorded history into the state
            const auto & hist = step["history"];
            const int hist_len = (int) hist[0].size();
            while (st.cur_len() < hist_len) {
                std::vector<int32_t> frame(9);
                for (int k = 0; k < 9; ++k) frame[k] = hist[k][st.cur_len()].get<int32_t>();
                st.append(frame);
            }
            std::vector<float> logits((size_t) 9 * vocab, 0.0f);
            st.process_logits(logits.data(), vocab);
            const auto & masked = step["eos_masked_rows"];
            for (int k = 0; k < 9; ++k) {
                const bool got = std::isinf(logits[(size_t) k * vocab + c.eos_id]);
                if (got != masked[k].get<bool>()) {
                    fprintf(stderr, "step %d codebook %d: eos_masked got=%d ref=%d "
                            "(pointer got=%d ref=%d)\n", step_idx, k, got,
                            (int) masked[k].get<bool>(), st.first_unfinished(),
                            step["pointer"].get<int>());
                    return fail("logits processor decision");
                }
            }
            if (st.first_unfinished() != step["pointer"].get<int>()) {
                fprintf(stderr, "step %d: pointer got=%d ref=%d\n", step_idx,
                        st.first_unfinished(), step["pointer"].get<int>());
                return fail("logits processor pointer");
            }
            step_idx++;
        }
        fprintf(stderr, "  logits-processor trace: %d steps ok\n", step_idx);
    }

    // ---- min_new_tokens gate + stopping + undelay roundtrip ----
    {
        delay_config c = cfg;
        c.max_length = 64;
        c.min_new_tokens = 10;
        delay_state st(c);
        const int vocab = 1088;
        std::vector<float> logits((size_t) 9 * vocab, 0.0f);
        st.process_logits(logits.data(), vocab);
        for (int k = 0; k < 9; ++k) {
            if (!std::isinf(logits[(size_t) k * vocab + c.eos_id])) {
                return fail("min_new_tokens must forbid eos at step 1");
            }
        }
        // feed 20 valid frames with known codes, then EOS cascade
        for (int t = 0; t < 20; ++t) {
            std::vector<int32_t> frame(9);
            for (int k = 0; k < 9; ++k) frame[k] = (t * 9 + k) % 1024;
            st.append(frame);
        }
        int guard = 0;
        while (!st.finished() && guard++ < 30) {
            std::vector<float> lg((size_t) 9 * vocab, 0.0f);
            st.process_logits(lg.data(), vocab);
            std::vector<int32_t> frame(9);
            for (int k = 0; k < 9; ++k) {
                // want EOS everywhere; the processor must veto all but the pointer
                frame[k] = std::isinf(lg[(size_t) k * vocab + c.eos_id]) ? 7 : c.eos_id;
            }
            st.append(frame);
        }
        if (!st.finished()) return fail("eos cascade did not finish");
        // cascade takes exactly 9 steps (one codebook per step)
        if (st.cur_len() != 1 + 20 + 9) {
            fprintf(stderr, "cur_len=%d expected %d\n", st.cur_len(), 1 + 20 + 9);
            return fail("cascade length");
        }
        int n_frames = 0;
        std::vector<int32_t> codes = st.undelay(1024, &n_frames);
        // roundtrip check against the accumulated sequence itself: frame t,
        // codebook k must equal seq[k][t+k+1], kept iff every codebook's
        // value at that slot is a real code (< 1024).
        const std::vector<int32_t> & seq = st.sequence();
        const int L = st.cur_len();
        int expect_frames = 0;
        std::vector<int32_t> expect_vals;
        for (int t = 0; t + 9 < L; ++t) {
            bool ok = true;
            for (int k = 0; k < 9; ++k) {
                if (seq[(size_t) k * L + (t + k + 1)] >= 1024) ok = false;
            }
            if (ok) expect_frames++;
        }
        if (n_frames != expect_frames) {
            fprintf(stderr, "undelay frames=%d expected %d\n", n_frames, expect_frames);
            return fail("undelay frame count");
        }
        for (int t = 0; t < n_frames; ++t) {
            for (int k = 0; k < 9; ++k) {
                const int32_t expect = seq[(size_t) k * L + (t + k + 1)];
                if (codes[(size_t) k * n_frames + t] != expect) {
                    return fail("undelay values");
                }
            }
        }
        fprintf(stderr, "  stopping + undelay: %d frames ok\n", n_frames);
    }

    fprintf(stderr, "parler delay: PASS\n");
    return 0;
}
